### ISSUE TITLE
Crashes when a Solidity method is named `receive`

### ISSUE THREAD

**Issue by k06a** [cgewecke/eth-gas-reporter#196]
Check very first commit of https://github.com/k06a/ShardedToken
```
yarn && yarn run test
```
```
yarn run v1.22.0
$ scripts/test.sh
Starting our own ganache instance
Truffle v5.1.15 (core: 5.1.15)
Solidity - 0.5.16 (solc-js)
Node v10.19.0
Web3.js v1.2.1

Compiling your contracts...
===========================
> Compiling ./contracts/IShardedToken.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/Sharded.sol
> Compiling ./contracts/ShardedToken.sol
> Compiling @openzeppelin/contracts/GSN/Context.sol
> Compiling @openzeppelin/contracts/math/SafeMath.sol
> Compiling @openzeppelin/contracts/ownership/Ownable.sol
> Artifacts written to /var/folders/6x/vgh3wd655gn6nt72hbqydd240000gn/T/test-202022-20389-b7tik4.tiuee
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

TypeError: Cannot read property '0' of null
    at ASTBuilder.ContractPart (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:127:35)
    at ASTBuilder.visit (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at ASTBuilder.<anonymous> (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1292:19)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1291:16)
    at ASTBuilder.ContractDefinition (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:113:22)
    at ASTBuilder.visit (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at ASTBuilder.<anonymous> (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1292:19)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1291:16)
    at ASTBuilder.SourceUnit (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:73:22)
    at ASTBuilder.visit (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/ASTBuilder.js:1304:38)
    at Object.parse (/Users/k06a/Projects/ShardedToken/node_modules/solidity-parser-diligence/dist/index.js:83:21)
    at Object.getContractNames (/Users/k06a/Projects/ShardedToken/node_modules/eth-gas-reporter/lib/utils.js:97:24)
    at files.forEach.file (/Users/k06a/Projects/ShardedToken/node_modules/eth-gas-reporter/lib/gasData.js:43:10)
    at Array.forEach (<anonymous>)
    at GasData.initialize (/Users/k06a/Projects/ShardedToken/node_modules/eth-gas-reporter/lib/gasData.js:41:11)
    at Runner.Gas.runner.on (/Users/k06a/Projects/ShardedToken/node_modules/eth-gas-reporter/index.js:45:16)
    at Runner.emit (events.js:203:15)
    at start (/Users/k06a/Projects/ShardedToken/node_modules/mocha/lib/runner.js:848:10)
    at Runner.run (/Users/k06a/Projects/ShardedToken/node_modules/mocha/lib/runner.js:876:5)
    at Mocha.run (/Users/k06a/Projects/ShardedToken/node_modules/mocha/lib/mocha.js:612:17)
Truffle v5.1.15 (core: 5.1.15)
Node v10.19.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cgewecke** [comment]
It looks like the new parser (upgraded to handle newer solc) is having a problem with [methods named receive][2]. This is [a Solidity keyword][1] in solc >= 0.6.x.

[1]: https://solidity.readthedocs.io/en/v0.6.3/060-breaking-changes.html#semantic-and-syntactic-changes
[2]: https://github.com/k06a/ShardedToken/blob/master/contracts/IShardedToken.sol#L17

**Comment by cgewecke** [comment]
@k06a If you downgrade and pin eth-gas-reporter at  `0.2.14` this problem should go away...

**Comment by k06a** [comment]
@cgewecke thanks, renamed the method. It would be great to see exact error description :)

**Comment by cgewecke** [comment]
> It would be great to see exact error description

Agree - usually the parser's able to identify the location of the failure but in this case it seems to be crashing because of an ambiguity in the grammar. Will investigate further.
