### ISSUE TITLE
Error: invalid fragment object

### ISSUE THREAD

**Issue by Wolf-Rost** [cgewecke/eth-gas-reporter#201]
Hi, 

I have a contract with the receive() function in it to be able to send ether to it. Without the eth-gas-reporter the test will just run fine. However, with the eth-gas-reporter I get the following error message:

```
> Compiled successfully using:
   - solc: 0.6.1+commit.e6f7d5a4.Emscripten.clang
Error: invalid fragment object (argument="value", value={"stateMutability":"payable","type":"receive"}, version=abi/5.0.0-beta.142)
```

Truffle v5.1.16 (core: 5.1.16)
Node v8.9.4

**Comment by cgewecke** [comment]
@Wolf-Rost Thanks for reporting. Could you show the complete output of the error?

**Comment by Wolf-Rost** [comment]
Please find the complete output of the error below:
<details>
<summary>Expand</summary>
```
Error: invalid fragment object (argument="value", value={"stateMutability":"payable","type":"receive"}, version=abi/5.0.0-beta.142)
    at Logger.makeError (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/@ethersproject/logger/lib/index.js:105:21)
    at Logger.throwError (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/@ethersproject/logger/lib/index.js:114:20)
    at Logger.throwArgumentError (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/@ethersproject/logger/lib/index.js:117:21)
    at Function.Fragment.fromObject (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/@ethersproject/abi/lib/fragments.js:369:23)
    at Function.Fragment.from (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/@ethersproject/abi/lib/fragments.js:350:25)
    at /Users/Juuu/CALYSTRAL/contracts/Other/node_modules/@ethersproject/abi/lib/interface.js:73:41
    at Array.map (<anonymous>)
    at new Interface (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/@ethersproject/abi/lib/interface.js:72:60)
    at utils.getContractNames.filter.forEach.name (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/calystral-eth-gas-reporter/lib/gasData.js:72:27)
    at Array.forEach (<anonymous>)
    at files.forEach.file (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/calystral-eth-gas-reporter/lib/gasData.js:45:10)
    at Array.forEach (<anonymous>)
    at GasData.initialize (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/calystral-eth-gas-reporter/lib/gasData.js:41:11)
    at Runner.Gas.runner.on (/Users/Juuu/CALYSTRAL/contracts/Other/node_modules/calystral-eth-gas-reporter/index.js:45:16)
    at emitNone (events.js:111:20)
    at Runner.emit (events.js:208:7)
    at start (/Users/Juuu/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:848:10)
    at Runner.run (/Users/Juuu/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:876:5)
    at Mocha.run (/Users/Juuu/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:612:17)
    at resolve (/Users/Juuu/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:145:1)
    at new Promise (<anonymous>)
    at Object.run (/Users/Juuu/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:144:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
</details>

**Comment by cgewecke** [comment]
The underlying issue is already being tracked at [ethers 746][1]. Have opened #202 to handle this more gracefully. 

Another dependency here, solidity-parser-diligence, also some lingering problems with solc 0.6.x syntax fwiw. 

[1]: https://github.com/ethers-io/ethers.js/issues/746
