### ISSUE TITLE
Error: Content needs to be a primitive, got: function

### ISSUE THREAD

**Issue by maurelian** [cgewecke/eth-gas-reporter#46]
```
// ^^ a bunch of tests passing, and then...  ^^
     ✓ should be able to withdraw via core as COO (45404 gas)
Gas spent on test suite: 44334524000000879275

/Users/primary/Projects/cryptokitties-bounty/node_modules/truffle/build/cli.bundled.js:320098
        throw reason;
        ^

Error: Content needs to be a primitive, got: function
    at Cell.setOptions (/Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/src/cell.js:27:11)
    at new Cell (/Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/src/cell.js:12:8)
    at /Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/src/layout-manager.js:157:16
    at arrayMap (/Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/node_modules/lodash/index.js:6710:14)
    at /Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/src/layout-manager.js:156:16
    at /Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/node_modules/lodash/index.js:2275:27
    at /Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/node_modules/lodash/index.js:3049:15
    at baseMap (/Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/node_modules/lodash/index.js:2274:7)
    at Function.map (/Users/primary/Projects/cryptokitties-bounty/node_modules/cli-table2/node_modules/lodash/index.js:6710:14)
npm ERR! Test failed.  See above for more details.```

**Comment by cgewecke** [comment]
Thanks for catching this. Something broke in an ascii colorization dep . . . should be fixed with `0.0.15`. Cryptokitties report below. (Run time is pretty slow, maybe 8 - 10 minutes).

Closing but please feel to reopen if not resolved.  

![cryptokitties](https://user-images.githubusercontent.com/7332026/33799176-48a6443a-dcdb-11e7-87f7-5bad48185e4a.png)
